# Organizations
Organizations:
    - &OrdererHF
        Name: OrdererHF
        ID: example.com
        AdminPrincipal: Role.ADMIN
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

    - &Org1HF
        Name: Org1HF
        ID: org1.example.com
        AdminPrincipal: Role.ADMIN
        MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
        AnchorPeers:
            - Host: peer0.org1.example.com
              Port: 7051

    - &Org2HF
        Name: Org2HF
        ID: org2.example.com
        AdminPrincipal: Role.ADMIN
        MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
        AnchorPeers:
            - Host: peer0.org2.example.com
              Port: 7051

# Orderer
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 5s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Organizations:

# Application
Application: &ApplicationDefaults
    Organizations:

# Profile
Profiles:
    OrdererHF:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererHF
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1HF
                - *Org2HF
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *OrdererHF
                    - *Org1HF
                    - *Org2HF